# Docker compose example
version: '3.9'
services:
  postgres:
    container_name: PG-DB
    image: postgres:13.6-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 09-831bf90831w7bf0e9qw
      POSTGRES_USER: PGUSER
      POSTGRES_DB: PGDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adonis-be:
    container_name: adonis-be
    image: adonis-be:latest
    ports:
      - 8012:8012
    restart: always
    environment:
      - PORT=8012
      - HOST=0.0.0.0
      - NODE_ENV=production
      - APP_KEY=0981wyuf9801we7f98sdqunf098wqd7
      - DRIVE_DISK=local
      - DB_CONNECTION=pg
      - PG_HOST=PG-DB
      - PG_PORT=5432
      - PG_USER=PGUSER
      - PG_PASSWORD=09-831bf90831w7bf0e9qw
      - PG_DB_NAME=PGDB
      - PAGINATION=10
      - S3_KEY=
      - S3_SECRET=
      - S3_BUCKET=
      - S3_REGION=

  nginx:
    container_name: nginx
    image: nginx:1.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
